/*
CREATE DATABASE WEBFUEL2
USE WEBFUEL2;

CREATE TABLE TESTE(

ID_TESTE  INTEGER AUTO_INCREMENT NOT NULL,
NOME      VARCHAR(50),
SOBRENOME VARCHAR(50),
DT_REG    TIMESTAMP,

PRIMARY KEY (ID_TESTE)
);
*/
drop table USUARIO;
CREATE TABLE USUARIO(

ID_USUARIO    INTEGER AUTO_INCREMENT NOT NULL,
ID_FACEBOOK   BIGINT, 
ID_CIDADE     INT(4),
NOME          VARCHAR(50),
SOBRENOME     VARCHAR(50),
SEXO          CHAR(1),
EMAIL         VARCHAR(60),
FOTO          VARCHAR(1000), 

PRIMARY KEY (ID_USUARIO)

)
ENGINE=InnoDB 
DEFAULT CHARSET=LATIN1 
COLLATE = latin1_general_ci;